version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HACKERNEWS_BASE_URL=https://hacker-news.firebaseio.com/v0/
      - DATABASE_URL=postgresql+asyncpg://postgres:prabha@postgres:5432/hn_search
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - hn_network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prabha
      - POSTGRES_DB=hn_search
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hn_network

  redis:
    image: redis:7
    networks:
      - hn_network

  celery_worker:
    build: .
    command: celery -A hn_search.celery_app worker --loglevel=info
    environment:
      - HACKERNEWS_BASE_URL=https://hacker-news.firebaseio.com/v0/
      - DATABASE_URL=postgresql+asyncpg://postgres:prabha@postgres:5432/hn_search
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - hn_network

  celery_beat:
    build: .
    command: celery -A hn_search.celery_app beat --loglevel=info
    environment:
      - HACKERNEWS_BASE_URL=https://hacker-news.firebaseio.com/v0/
      - DATABASE_URL=postgresql+asyncpg://postgres:prabha@postgres:5432/hn_search
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - hn_network

networks:
  hn_network:
    driver: bridge

volumes:
  postgres_data:
